name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            #!/usr/bin/expect -f
            set user jumpinto
            set host 77.222.56.16
            set password ekfihariuf
            set timeout -1
            spawn ssh  $user@$host
            expect "*password:*"
            send "$password\r"
            interact
            rsync /Users/tonyrush/WebstormProjects/hyggeboksen_TM jumpinto@hyggeboksen.ru:/hyggeboksenTM/public_html/
          always-auth: true
#      # Setup key
#      - run: set -eu
#      - run: mkdir "$HOME/.ssh"
#      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
#      - run: chmod 600 "$HOME/.ssh/key"

      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
#      - run: cd dist && sshpass -p "ekfihariuf" rsync -ae "ssh -p 22" /Users/tonyrush/WebstormProjects/hyggeboksen_TM jumpinto@hyggeboksen.ru:/hyggeboksenTM/public_html/